### ISSUE TITLE
How do you measure the PSNR of test set for N3DV in Table 1?

### ISSUE THREAD

**Issue by johnnylu305** [AlgoHunt/StreamRF#1]
Hi, thank you for your excellent work. I download the flame_salmon dataset from N3DV GitHub. After I unzipped it, it contained 40-second video for 19 cameras. I assume you use cam01~cam20 for training and cam00 for testing. Instead of measuring the PSRN every 10 frames, you measure the PSNR per frame, which is first 300 frames from cam00. Do you only report the PSNR for the first 10-second frames? Or, you split them into four chunks (each video is 10 seconds), train the model per chunk, and then measure the average PSNR between them?

**Comment by AlgoHunt** [comment]
We use the flame_salmon's cam00 as test set and report the average PSNR of first 300 frames as in the N3DV's paper (Table 1).

**Comment by johnnylu305** [comment]
Got it. Thank you.
