### ISSUE TITLE
Train/Val split of the Meeting Room Dataset

### ISSUE THREAD

**Issue by JokerYan** [AlgoHunt/StreamRF#10]
Maybe I overlooked somewhere, but may I ask what is the train/validation split of the meeting room dataset. 
Is the cam_0 used for validation?

Thank you!

**Comment by AlgoHunt** [comment]
Yes you are right, we use cam_0(which is the center camera) for testing.

**Comment by JokerYan** [comment]
@AlgoHunt Ok thank you very much!
