### ISSUE TITLE
Question about experiments on the MeetRoom dataset

### ISSUE THREAD

**Issue by SJoJoK** [AlgoHunt/StreamRF#13]
Hello, Thanks for your great job!

I'm conducting experiments on the MeetRoom dataset, since there are three scenes in Google Drive and four scenes in ModelScope. I'd like to ask which scenes the results in Table 1 are averaged from?

Thanks in advance for any help.

**Comment by Spark001** [comment]
Hi SJoJoK,

The result in paper was obtained from scene `discussion`.

Best regards,
Zhen Shen

**Comment by SJoJoK** [comment]
Got it, thanks:)
