### ISSUE TITLE
A problem about Initialization training on Plenoxels

### ISSUE THREAD

**Issue by Winter-Dry** [AlgoHunt/StreamRF#2]
Thanks for your wonderful work, could please provide the detailed training config on Plenoxels that related to the Meetroom dataset.
I'm trying to reimplement the experiments on  Meetroom dataset but I got poor results on the first frame model trained by Plenoxels.

**Comment by AlgoHunt** [comment]
I have updated the config and added the relevant commands for initialization. please refer to the latest commit.

**Comment by Winter-Dry** [comment]
> 

Thanks a lot
