### ISSUE TITLE
Where is opt.py file as in the README.md for training?

### ISSUE THREAD

**Issue by devinluo27** [AlgoHunt/StreamRF#3]

**Comment by AlgoHunt** [comment]
refer to the plenoxels‘ repository [svox2](https://github.com/sxyu/svox2)

**Comment by devinluo27** [comment]
TBH, I did try opt/opt.py in svox2, but problems still exists. For example, opt.py of svox2 does not have the argument "offset" and your script yields an error. 

I would appreciate that you authors could provide an actually runnable script and double check it before uploading.

**Comment by Spark001** [comment]
Please check the lastest commit, and we reproduce the result on a clean machine.

The instruction has been double checked:
* clone & install the `svox2` and some necessary packages
* prepare the dataset
* run the three command
