### ISSUE TITLE
the problem of dataset

### ISSUE THREAD

**Issue by beibeirory** [AlgoHunt/StreamRF#4]
I got an error like the followings, can you give me a favor?

Defaulting to extended NSVF dataset

LOAD NSVF DATA /home/llh/experiments/Downloads/MeetRoom-20221231T025252Z-001/MeetRoom/ split train

Traceback (most recent call last):

  File "opt.py", line 271, in <module>

    dset = datasets[args.dataset_type](

  File "/home/llh/experiments/code/StreamRF-main/util/dataset.py", line 20, in auto_dataset

    return NSVFDataset(root, *args, **kwargs)

  File "/home/llh/experiments/code/StreamRF-main/util/nsvf_dataset.py", line 82, in __init__

    img_dir_name = look_for_dir(["images", "image", "rgb"])

  File "/home/llh/experiments/code/StreamRF-main/util/nsvf_dataset.py", line 79, in look_for_dir

    assert False, "None of " + str(cands) + " found in data directory"

AssertionError: None of ['images', 'image', 'rgb'] found in data directory

munmap_chunk(): invalid pointer

Aborted (core dumped)

**Comment by AlgoHunt** [comment]
Hi, What is your dataset structure? 
The default dataset type we use is LLFF. Take flamon_salmon_1 for example the dataset folder should be some thing like this:

```
flamon_salmon_1
├── 0000    
...
└── 0299 
    ├── pose_bounds.npy  
    └── images
        └── cam[00/01/02/.../20].png
```

**Comment by beibeirory** [comment]
I download your dataset Meet Room Dataset and use it. The dataset only contains videos. Should I prepare the dataset folder by myself?

**Comment by beibeirory** [comment]
> Hi, What is your dataset structure? The default dataset type we use is LLFF. Take flamon_salmon_1 for example the dataset folder should be some thing like this:
> 
> ```
> flamon_salmon_1
> ├── 0000    
> ...
> └── 0299 
>     ├── pose_bounds.npy  
>     └── images
>         └── cam[00/01/02/.../20].png
> ```
Could you tell me how to prepare the dataset folder?
0000-0299 refer to the number of video streams? What does the pose_bounds.npy store for the images folder?

**Comment by beibeirory** [comment]
> Hi, What is your dataset structure? The default dataset type we use is LLFF. Take flamon_salmon_1 for example the dataset folder should be some thing like this:
> 
> ```
> flamon_salmon_1
> ├── 0000    
> ...
> └── 0299 
>     ├── pose_bounds.npy  
>     └── images
>         └── cam[00/01/02/.../20].png
> ```

Thanks for your reply. 
I prepare the dataset folder like "flamon_salmon_1", but the problem exists. I check your code "llff_dataset.py", and find that the dataset folder is like this:
├── pose_bounds.npy  
>     └── images
>         └── cam[00/01/02/.../20].png
1、It can not handle different views.  Please let me know if there is a problem with my operation.
2、I got another problem. 
"Morton code requires a cube grid of power-of-2 size, ignoring...
Segmentation fault (core dumped)"
It looks like there is something wrong with "grid. svox2.SparseGrid()" in "opt.py".

**Comment by devinluo27** [comment]
Similar problem here @beibeirory ! Just don't know how the authors get through this code and run their experiments.

**Comment by Spark001** [comment]
Please check the latest commit, I update a script to prepare dataset.
