### ISSUE TITLE
Would you mind to share pretrained model and testing video of flame_salmon?

### ISSUE THREAD

**Issue by johnnylu305** [AlgoHunt/StreamRF#7]
Hello, thank you for releasing the code and the demo video. Would you mind to share pretrained model and predicted testing video (cam00) of flame_salmon?

**Comment by Spark001** [comment]
I update the test video for flame_salmon on https://drive.google.com/drive/folders/1neezi9ZXiVjKblMbcEftID2tY3FDR4Wt?usp=share_link
