### ISSUE TITLE
Artifacts during training the full model

### ISSUE THREAD

**Issue by YuanxunLu** [AlgoHunt/StreamRF#9]
Hi,
    Thanks for your impressive work! I'm trying to run the code following the instructions on the MeetRoom dataset. However, I found that the final generation result is bad with clear time consistency and block artifacts. Specifically, this happens after training the full model (the pilot model seems good, see the videos below). I tried on all 3 scenes of the MeetRoom dataset, and the artifacts appear on all these scenes. Is there any bug in the "train_video_n3dv_full.py" file? like some missing input arguments or wrong hyperparameters?
    Hope for your feedback!

The pilot model of scene "discussion":
https://user-images.githubusercontent.com/35017815/220124406-f7863a9c-591a-4f70-a12a-a6da89d5f3d9.mp4

The full model of scene "discussion":
https://user-images.githubusercontent.com/35017815/220124483-e0dd4b0e-a66e-48cd-a86f-72e41e342010.mp4

The pilot model of scene "vrheadset":
https://user-images.githubusercontent.com/35017815/220124677-f264adec-abdc-46dd-8eea-ea11ef7e7def.mp4

The full model of scene "vrheadset":
https://user-images.githubusercontent.com/35017815/220124801-47d75b9c-b018-4222-9e32-bae3aaec6ddb.mp4

**Comment by AlgoHunt** [comment]
Could you provide the commands you use and the log file, I clone the code and rerun it but didn't witness similar artifacts.

**Comment by YuanxunLu** [comment]
Thanks for your reply! 
In my experiments, I clone the repo, install the svox2 repo following the instructions, and run the scripts you provided. Specifically, there's a bug directly running the "opt.py" file, which is a 'Tensor' to 'numpy' transformation bug, but I think it is not important.

Here is my command line to run the three files:

step 1: python opt.py  -t meetroom_tri /media/yuanxun/E/Dataset/MultiViewVideos/MeetRoom/trimming/0000 -c configs/meetroom_init.json --scale 1.0

step 2: python train_video_n3dv_pilot.py -t meetroom_tri /media/yuanxun/E/Dataset/MultiViewVideos/MeetRoom/trimming -c configs/meetroom.json --batch_size 20000   --pretrained meetroom_tri/ckpt.npz  --n_iters 1000    --lr_sigma 0.3  --lr_sigma_final 0.3  --lr_sh 1e-2 --lr_sh_final 1e-4 --lr_sigma_decay_steps 1000 --lr_sh_decay_steps 1000   --frame_end 300 --fps 30 --train_use_all 0 --scale 1.0 --sh_keep_thres 1.0 --sh_prune_thres 0.1 --performance_mode  --dilate_rate_before 1 --dilate_rate_after 1 --stop_thres 0.01  --compress_saving --save_delta   --pilot_factor 2 

step 3: python train_video_n3dv_full.py -t meetroom_tri /media/yuanxun/E/Dataset/MultiViewVideos/MeetRoom/trimming -c configs/meetroom_full.json --batch_size 20000   --pretrained meetroom_tri/ckpt.npz  --n_iters 500    --lr_sigma 1.0 --lr_sigma_final 1.0  --lr_sh 1e-2 --lr_sh_final 1e-2 --lr_sigma_decay_steps 500 --lr_sh_decay_steps 500   --frame_end 300 --fps 30 --train_use_all 0 --scale 1.0 --sh_keep_thres 1.5 --sh_prune_thres 0.3 --performance_mode  --dilate_rate_before 2 --dilate_rate_after 2    --compress_saving --save_delta  --apply_narrow_band 

and the two log file of the trimming scene:

[log_pilot.log](https://github.com/AlgoHunt/StreamRF/files/10792033/log_pilot.log)

[log_full.log](https://github.com/AlgoHunt/StreamRF/files/10792035/log_full.log)


Thanks for your timely reply again! and hope for your feedback!

**Comment by Spark001** [comment]
@YuanxunLu  
Oh, I know the reason.

You use the same log_dir in pilot model and full model training. The ckpt.npz trained by initialized frame was replaced by the pilot model training. So the full model training got a wrong ckpt to initialize : (

Anyway, we fix the saved npz name in pilot model training. You can get the latest code and train again.

**Comment by YuanxunLu** [comment]
Thanks! I'll try the latest code!
